### ISSUE TITLE
Failed test 'done_testing() was already called at t/45-params.t

### ISSUE THREAD

**Issue by eserte** [stevieb9/async-event-interval#5]
On some of my smoker systems the test suite fails like this:
```
#   Failed test 'done_testing() was already called at t/45-params.t line 26'
#   at t/45-params.t line 26.
t/45-params.t .......... 
All 3 subtests passed 
```

**Comment by stevieb9** [comment]
Disabled ability for the event to run more than once, preventing the scenario described in the problem statement. Fixed in 4855871
